### ISSUE TITLE
read.beast.table removed?

### ISSUE THREAD

**Issue by fhafarache** [heibl/ips#8]
Hello,

In R 4.0.2 (om MacOSX) I tried:

install.packages("ips")
library(ips)
?read.beast()
?read.beast.table()

Were these functions removed from ips?

Thanks

Fernando

**Comment by heibl** [comment]
Hi Fernando,

no, they were not removed, but the are currently not exported to the package's namespace, because they are somewhat outdated. You can still call them with ips:::read.beast and ips:::read.beast.table. Or you might like to the treeio package, which has a lot of up-to-date functionality for BEAST trees. If you insist to have them in the namespace you have to be patient because I will be in hospital for at least the next three weeks.

Best, Christoph

**Comment by fhafarache** [comment]
Hello Christoph,

Many thanks for the prompt reply. I will check treeio. I have tried ips:::read.beast.table and works fine.

Hope you are doing well, and wishing you a quick recovery.

Best wishes,

Fernando

**Comment by heibl** [comment]
read.beast and read.beast.table are now exported to the package namespace again.

**Comment by fhafarache** [comment]
This is great! many thanks!
